### ISSUE TITLE
iOS deep link issue

### ISSUE THREAD

**Issue by aamir-ans** [CleverTap/clevertap-react-native#125]
@Aditi3 
Hi I'm facing issue regarding notification: 
- When iOS app is completely closed and click on notification deep linking is not working.
- When app is in foreground can't get notification.
Please help me on this.

**Comment by Aditi3** [comment]
Hi @aamir-ans 

Answer to your queries described in the issue:

### When the iOS app is completely closed and click on notification deep linking is not working.

This seems to be unexpected behaviour. Hence, I would recommend writing to CleverTap Support Team with the Campaign link and integration details so that we can look into this further. 

### When the app is in foreground can't get a notification.

For receiving notifications while the app is in the foreground, add the following method in your App Delegate class:

```
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) 
{
    completionHandler([.alert, .badge, .sound])
}
```

Also, you need to register your App Delegate as the delegate for the notifications center:

```
import UserNotifications

class AppDelegate : UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

      // set the delegate in didFinishLaunchingWithOptions
      UNUserNotificationCenter.current().delegate = self
      ...
}
```


Refer to the [Apple Documention](https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions) for more details about handling notifications while your app runs in the foreground.

Hope this helps!

**Comment by aamir-ans** [comment]
Thanks @Aditi3 solution works.

**Comment by Aditi3** [comment]
Wonderful, great to know! Thanks so much for letting us know. Glad to hear this has been resolved.

**Comment by aamir-ans** [comment]
@Aditi3  When click on notification in iOS some deep link URL opens safari browser ? any specific use case I'm missing? I have defined URL schemes as well but still redirecting  to safari browser

**Comment by quoctruongkt** [comment]
Same problem and I still don't have any solution to deal with it

**Comment by KshitizVaya12** [comment]
I'm facing an issue where deep linking from push notifications works correctly on iOS when the app is in the foreground or background. However, when the app is in a terminated (cold start) state, tapping the push notification simply opens the app to the home screen, and the deep link is not triggered or handled.

How can I correctly extract and handle the deep link from the notification payload when the app is launched from a quit state?
